<a href="https://colab.research.google.com/github/abhiart1katiyar/ml-codingblocks/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install numpy 
# Multi-Dimentional Array Library

In [40]:
import numpy as np
nparray = np.array([[1,2,3,4],[5,6,7,8]], dtype='int8')
print(nparray)
print(nparray.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [2]:
print(nparray[0,3])

4


In [3]:
print(nparray.shape)
print(nparray.itemsize)
print(nparray.dtype)
print(nparray.nbytes) # No. of bytes each element takes


(2, 4)
1
int8
8


In [4]:
arrA = np.array([[1,2],[5,6]], dtype='int8')
arrB = np.array([[4,7],[8,9]], dtype='int8')
np.dot(arrA,arrB) # Matrix multiplication
arrC = arrA * arrB # arrA i,j * arrB i,j
print(arrC)

[[ 4 14]
 [40 54]]


In [5]:
print(arrA[1:][0:])

[[5 6]]


In [ ]:
print(nparray[1:])

[[5 6 7 8]]


In [ ]:
print(nparray[:,2]) # each row but 2nd column
print(nparray[0,:]) # 0th row and all column
print(nparray[0,3]) # 0th row and 3rd column

[3 7]
[1 2 3 4]
4


In [10]:
print(nparray[0,0:4:2]) # 0th row , from 0th column till column 3(i.e. 4-1) with step size as 2

[1 3]


In [11]:
print(np.flip(nparray[0,0:4:1],0)) # 0th row , from 0th column till column 3(i.e. 4-1) with step size as 2

[4 3 2 1]


In [13]:
print(nparray[0:,0:3:1]) # 0th row , from 0th column till column 3(i.e. 4-1) with step size as 2

[[1 2 3]
 [5 6 7]]


In [ ]:
print(np.flip(nparray[0:,0:-1:1],0)) # 0th row , from 0th column till column 3(i.e. 4-1) with step size as 2 ... , 0 for vertical flip

[[5 6 7]
 [1 2 3]]


In [ ]:
print(np.flip(nparray[0:,0:-1:1],1)) # 0th row , from 0th column till column 3(i.e. 4-1) with step size as 2 ... , 1 for horizontal flip

[[3 2 1]
 [7 6 5]]


In [ ]:
print(nparray)
print("----")
print(nparray[0:,2]) # print column 2(index wise)
print("Now focus here..")
nparray[0:,2] = 999
print(nparray)

[[1 2 3 4]
 [5 6 7 8]]
----
[3 7]
Now focus here..
[[  1   2 -25   4]
 [  5   6 -25   8]]


In [16]:
array_cus = np.ones((5,5), dtype='int32')
#print(array_cus)
array_cus[1:4,1:4] = np.zeros((3,3), dtype='int32')
array_cus[2,2]=9
print(array_cus)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [36]:
## Some more info
import ctypes
print(array_cus.flags)
print(array_cus.shape)
print(array_cus.ndim)
print(array_cus.ctypes.data_as(ctypes.POINTER(ctypes.c_uint32)).contents)
print(array_cus.size)
print(array_cus.itemsize)
print(array_cus.nbytes)


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

(5, 5)
2


TypeError: ignored

In [29]:
print(array_cus.T)
complex_arr = np.array([[1+2j, 3+6j],[1+5j, 5+7j]],dtype='complex128')
print(np.sqrt(complex_arr))
print(complex_arr[0][0].real)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1.27201965+0.78615138j 2.20320266+1.36165413j]
 [1.74628456+1.4316109j  2.60790388+1.342074j  ]]
1.0


**Reshaping the Array**

In [44]:
init_array = np.array([[1,2,3],[4,5,6]])
print(init_array)
reshaped_array = init_array.reshape(1,6)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
